# config.yaml is used when you need to test the compatibility of multiple Redis-Like
# systems and generate html reports (--genhtml)

# html report directory
Dir: "html"

# specify test version
SpecificVersion:
  - 4.0.0
  - 5.0.0
  - 6.0.0
  - 7.0.0

# the host, port, password of all the db to be tested
Database:
  RedisCommunity:
    host: 172.16.0.10
    port: 6379
    password:
    ssl: false
    cluster: false
    version: latest

  DragonflyDB:
    host: 172.16.0.10
    port: 6380
    password:
    ssl: false
    cluster: false
    version: latest

  Kvrocks:
    host: 172.16.0.10
    port: 6381
    password:
    ssl: false
    cluster: false
    version: latest

  KeyDB:
    host: 172.16.0.10
    port: 6382
    password:
    ssl: false
    cluster: false
    version: latest

  Pika:
    host: 172.16.0.10
    port: 6383
    password:
    ssl: false
    cluster: false
    version: latest

  ElastiCache:
    host:
    port:
    password:
    ssl:
    cluster: false
    version:

  MemoryDB:
    host:
    port:
    password:
    ssl:
    cluster: false
    version:

  AzureRedis:
    host:
    port:
    password:
    ssl:
    cluster: false
    version:

  GoogleMemoryStore:
    host:
    port:
    password:
    ssl:
    cluster: false
    version:

  TencentRedis:
    host:
    port:
    password:
    ssl:
    cluster: false
    version:

  GaussDBRedis:
    host:
    port:
    password:
    ssl:
    cluster: false
    version:
