# config.yaml is used when you need to test the compatibility of multiple Redis-Like
# systems and generate html reports (--genhtml)

# html report directory
Dir: "html"

# specify test version
SpecificVersion:
  - 4.0.0
  - 5.0.0
  - 6.0.0
  - 7.0.0

# the host, port, password of all the db to be tested
Database:
  Redis:
    host: 127.0.0.1
    port: 6379
    password:
    ssl: false
    cluster: false
    version: unstable

  DragonflyDB:
    host: 127.0.0.1
    port: 6380
    password:
    ssl: false
    cluster: false
    version: latest

  Kvrocks:
    host: 127.0.0.1
    port: 6381
    password:
    ssl: false
    cluster: false
    version: 2.2.0

  KeyDB:
    host: 127.0.0.1
    port: 6382
    password:
    ssl: false
    cluster: false
    version: latest

  Pika:
    host: 127.0.0.1
    port: 6383
    password:
    ssl: false
    cluster: false
    version: latest

  Tair:
    host:
    port:
    password:
    ssl:
    cluster: false
    version:
    access_key:
    access_key_secret:

  Kvstore:
    host:
    port:
    password:
    ssl:
    cluster: false
    version:

  # Amazon ElastiCache for Redis
  ElastiCache:
    host:
    port:
    password:
    ssl:
    cluster: false
    version:
    access_key:
    access_key_secret:

  # Amazon MemoryDB for Redis
  MemoryDB:
    host:
    port:
    password:
    ssl:
    cluster: false
    version:

  AzureRedis:
    host:
    port:
    password:
    ssl:
    cluster: false
    version:
    access_key:
    access_key_secret:

  GoogleMemoryStore:
    host:
    port:
    password:
    ssl:
    cluster: false
    version:
    access_key:
    access_key_secret:

  TencentRedis:
    host:
    port:
    password:
    ssl:
    cluster: false
    version:
    access_key:
    access_key_secret:

  GaussDBRedis:
    host:
    port:
    password:
    ssl:
    cluster: false
    version:
    access_key:
    access_key_secret: