name: unstable

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-with-redis-unstable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: clone and build redis
        run: |
          sudo apt-get install git
          git clone https://github.com/redis/redis
          cd redis
          make -j

      - name: start redis
        run: |
          ./redis/src/redis-server &

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: install requirements
        run: pip install -r requirements.txt

      - name: run test
        run: python redis_compatibility_test.py --testfile cts.json --show-failed > test.result

      - name: check fail tests
        run: |
          cat test.result
          grep -q "This is failed tests for" test.result && exit -1 || exit 0
